# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20180415_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='url',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
